"""
Author: Team 8
City: Chicago
Subject: COMP90024
"""
lang_codes = {
    "fr": {"name": "French", "status": "production"},
    "en": {"name": "English", "status": "production"},
    "ar": {"name": "Arabic", "status": "production"},
    "ja": {"name": "Japanese", "status": "production"},
    "es": {"name": "Spanish", "status": "production"},
    "de": {"name": "German", "status": "production"},
    "it": {"name": "Italian", "status": "production"},
    "id": {"name": "Indonesian", "status": "production"},
    "in": {"name": "Indonesian", "status": "production"},
    "pt": {"name": "Portuguese", "status": "production"},
    "ko": {"name": "Korean", "status": "production"},
    "tr": {"name": "Turkish", "status": "production"},
    "ru": {"name": "Russian", "status": "production"},
    "nl": {"name": "Dutch", "status": "production"},
    "fil": {"name": "Filipino", "status": "production"},
    "tl": {"name": "Tagalog", "status": "production"},
    "msa": {"name": "Malay", "status": "production"},
    "zh-tw": {"name": "Traditional Chinese", "status": "production"},
    "zh-cn": {"name": "Simplified Chinese", "status": "production"},
    "hi": {"name": "Hindi", "status": "production"},
    "no": {"name": "Norwegian", "status": "production"},
    "sv": {"name": "Swedish", "status": "production"},
    "fi": {"name": "Finnish", "status": "production"},
    "da": {"name": "Danish", "status": "production"},
    "pl": {"name": "Polish", "status": "production"},
    "hu": {"name": "Hungarian", "status": "production"},
    "ht": {"name": "Haitian Creole", "status": "production"},
    "fa": {"name": "Persian", "status": "production"},
    "he": {"name": "Hebrew", "status": "production"},
    "th": {"name": "Thai", "status": "production"},
    "et": {"name": "Estonian", "status": "production"},
    "lt": {"name": "Lithuanian", "status": "production"},
    "uk": {"name": "Ukrainian", "status": "production"},
    "cs": {"name": "Czech", "status": "production"},
    "ro": {"name": "Romanian", "status": "production"},
    "en-gb": {"name": "British English", "status": "production"},
    "vi": {"name": "Vietnamese", "status": "production"},
    "bn": {"name": "Bengali", "status": "production"},
    "und": {"name": "Undetermined", "status": "production"}
}
